[
  "Abaddon",
  "Alchemist",
  "Ancient Apparition",
  "Anti-Mage",
  "Axe",
  "Bane",
  "Batrider",
  "Beastmaster",
  "Bloodseeker",
  "Bounty Hunter",
  "Brewmaster",
  "Bristleback",
  "Broodmother",
  "Centaur Warruner",
  "Chaos Knight",
  "Chen",
  "Clinkz",
  "Clockwerk",
  "Crystal Maiden",
  "Dark Seer",
  "Dazzle",
  "Death Prophet",
  "Disruptor",
  "Doom",
  "Dragon Knight",
  "Drow",
  "Earth Spirit",
  "Earthshaker",
  "Elder Titan",
  "Ember Spirit",
  "Enchantress",
  "Enigma",
  "Faceless Void",
  "Gyrocoptor",
  "Huskar",
  "Invoker",
  "Io",
  "Jakiro",
  "Juggernaut",
  "Keeper of the Light",
  "Kunkka",
  "Legion Commander",
  "Leshrac",
  "Lich",
  "Lifestealer",
  "Lina",
  "Lion",
  "Lone Druid",
  "Luna",
  "Lycan",
  "Magnus",
  "Medusa",
  "Meepo",
  "Mirana",
  "Morphling",
  "Naga Siren",
  "Nature's Prophet",
  "Necrophos",
  "Night Stalker",
  "Nyx Assassin",
  "Ogre Magi",
  "Omni Knight",
  "Outworld Devourer",
  "Phantom Assassin",
  "Phantom Lancer",
  "Phoenix",
  "Puck",
  "Pudge",
  "Pugna",
  "Queen of Pain",
  "Razor",
  "Riki",
  "Rubick"
].each do |name|
  Hero.create(name: name)
end
